### ISSUE TITLE
Lab5

### ISSUE THREAD

**Issue by ZakharLuchinin** [dalafik/db#1]
1. Для того, чтобы не было проблем с кодировкой используется префикс N у строк. Это позволяет преобразования в юникод. Например, WHERE h.name = N'Космос'.

2.  Задание 4. Дать количество проживающих в гостинице “Космос” на 23 марта по каждой категории номеров.
Замечание: группировка по имени нежелательна. Операция по строке медленная. Можно получить неверный результат если будут разные категории с одним именем.

3. Задание 5. Дать список последних проживавших клиентов по всем комнатам гостиницы “Космос”, выехавшим в апреле с указанием даты выезда. 
Замечание: с целью оптимизации можно из подзапроса достать не только id_room, но и дату выезда, что позволит больше не цеплять таблицу room_in_booking. Ниже представлен синтаксис
JOIN ( SQL запрос ) last_checkout (id_room, checkout_date) ON rib.id_room = last_checkout.id_room AND rib.checkout_date = last_checkout.checkout_date

4. Задание 7. Найти все "пересекающиеся" варианты проживания.
Замечание: Запрос возвращает не все варианты. Пример не найденных записей
id_room_in_booking	id_booking	id_room	checkin_date	checkout_date
5	5	42	2019-03-19	2019-03-20
2154	1286	42	2019-03-17	2019-03-21

5. Задание 8. Создать бронирование в транзакции.  
Уровень SERIALIZABLE очень дорогой, для данного запроса хватит READ COMMITTED.
Использование IDENT_CURRENT не безопасно, т.к. возвращается последний id всех сессий ( https://docs.microsoft.com/en-us/sql/t-sql/functions/ident-current-transact-sql?view=sql-server-ver15 ). Лучше использовать SCOPE_IDENTITY().
https://docs.microsoft.com/en-us/sql/t-sql/functions/scope-identity-transact-sql?view=sql-server-ver15

6. Задание 9. Добавить необходимые индексы для всех таблиц.
Замечание: Не все индексы. Например, в задании 3 есть условие поиска rib.checkin_date <= @date3 AND @date3 < rib.checkout_date. Нет составного индекса.
Не забываем про использование INCLUDE.

7. Общая рекомендация. Желательно избегать лишних операций JOIN и заменять их на подзапросы. Например, если нам надо найти гостиницу Космос, то в подзапросе можно найти нужный нам id.

8. Общая рекомендация. Надо добавлять индекс на атрибуты по которым происходит JOIN

**Comment by dalafik** [comment]
Поправил, кроме задания 5 - таблица room_in_booking все равно нужна, чтобы выйти на клиента

**Comment by ZakharLuchinin** [comment]
Работу принял.

Задание 4. Дать количество проживающих в гостинице “Космос” на 23 марта по каждой категории номеров.
