### ISSUE TITLE
Лаб 7

### ISSUE THREAD

**Issue by ZakharLuchinin** [dalafik/db#2]
1. Задание 2. Выдать оценки студентов по информатике, если они обучаются данному предмету. Оформить выдачу данных с использованием view.
В выдаче у студентки Канаша Василиса Михаиловна (id = 40) дата NULL, оценка NULL. Таких записей не должно быть.

2. Задание 5. Дать оценки студентов специальности ВМ по всем проводимым предметам с указанием группы, фамилии, предмета, даты. При отсутствии оценки заполнить значениями NULL поля оценки.
Не все результаты возвращаются. Например, у студента Достовалов Карп Демьянович (id = 5, id группы 3) нет оценки NULL по предмету БД (id = 1) за урок 2019-05-07 (id урока 44)

**Comment by dalafik** [comment]
1. Я посчитал условие после "если", как имеющее первостепенное значение (в журнале учета успеваемости по предмету должны быть перечислены все обучающиеся ему студенты, а не только с оценками). Для удаления из выборки студентов без оценок нужно в строке 65 заменить LEFT JOIN на [INNER] JOIN.

2. Из текста задания не очевидно, что NULL нужно указывать для каждого урока по предмету без оценки. Я прочитал задание как: "Дать **полученные** оценки студентов специальности ВМ по всем проводимым предметам с указанием группы, фамилии, предмета, даты. При отсутствии **хотя бы одной оценки по предмету** заполнить значениями NULL поля оценки". Поскольку у данного студента есть оценки по предмету БД, то записи с NULL у него нет.

Добавлю, что у меня полетел SSD вскоре после коммита этой лабы, и, чтобы не ставить SQL Server заново, прошу рассмотреть возможность принятия этих заданий в такой редакции.

**Comment by ZakharLuchinin** [comment]
Принимаю, решение обосновано
